global:
  scrape_interval: 55s
  scrape_timeout: 55s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ["server_IP:port"]
        labels:
          instance: 'server_name'


  - job_name: 'cadvisor-exporter'
    static_configs:
      - targets: ['server_IP:port']
        labels:
          server_name: 'server_name'


  - job_name: 'container-exporter'
    static_configs:
      - targets: ['server_IP:port']
        labels:
          server_name: 'server_name'

  - job_name: 'mysql-exporter'
    static_configs:
      - targets: ['server_IP:port']
        labels:
          server_name: 'server_name'

  - job_name: 'docker-daemon'
    static_configs:
      - targets: ['server_IP:port']
        labels:
          server_name: 'server_name'

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Use the module we defined
    static_configs:
      - targets:
        - https://server_IP:port  # Target to probe

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: host_name:port
