# Blackbox Exporter Configuration
modules:
  http_2xx:
    prober: http
    http:
      preferred_ip_protocol: "ip4"
      tls_config:
        insecure_skip_verify: true  # Important: This allows probing with self-signed certs
      fail_if_not_ssl: true  # Ensure it's using HTTPS